export const quoteOptions = {
  servicioInteres: [
    "Automatización de procesos",
    "Agentes e inteligencia artificial",
    "Datos y Business Intelligence",
    "Machine Learning",
    "Simulación y optimización",
    "Visión por computadora",
    "Integraciones y cloud",
    "Aplicación web o MVP",
    "Necesito orientación",
  ],
  presupuestoEstimado: [
    "Necesito una recomendación",
    "Menos de $15,000 MXN",
    "$15,000–$40,000 MXN",
    "$40,000–$100,000 MXN",
    "$100,000–$250,000 MXN",
    "Más de $250,000 MXN",
  ],
  plazo: [
    "Por definir",
    "Menos de un mes",
    "1–3 meses",
    "3–6 meses",
    "Más de 6 meses",
  ],
  usuarios: [
    "Por definir",
    "1–10",
    "11–50",
    "51–200",
    "Más de 200",
    "Público externo",
  ],
  volumen: [
    "Por definir",
    "Hasta 100",
    "101–1,000",
    "1,001–10,000",
    "Más de 10,000",
  ],
  datos: [
    "No sé todavía",
    "Excel o archivos",
    "Base de datos",
    "API disponible",
    "Papel o sin digitalizar",
    "Varias fuentes",
  ],
  soporte: [
    "Por definir",
    "Solo implementación",
    "Implementación y soporte mensual",
  ],
} as const;
